apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webdephpa
  namespace: devns
  labels:
    app: web
spec:
  maxReplicas: 4
  minReplicas: 3
  targetCPUUtilizationPercentage: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webdep