apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvctest
  namespace: devns
#  labels:
#    app: db
#    env: dev
spec:
#  selector:
#    matchLabels:
#      app: db
#      env: dev
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi