apiVersion: v1
kind: Service
metadata:
  name: lbsvc
  namespace: devns
spec:
#  type: LoadBalancer
  selector:
    app: db
    env: dev
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql